"""Optional pooled PostgreSQL store. Importing this module needs no driver."""
from contextlib import contextmanager
import hashlib
import re
import threading

from .store_base import Store, identifier

_POOLS = {}
_POOL_LOCK = threading.Lock()


class Row(dict):
    def __getitem__(self, key):
        return tuple(self.values())[key] if isinstance(key, int) else super().__getitem__(key)


class Result:
    def __init__(self, cursor, generated=False):
        self.rowcount = cursor.rowcount
        self._rows = [Row(r) for r in cursor.fetchall()] if cursor.description else []
        self.lastrowid = self._rows[0][0] if generated and self._rows else None

    def fetchone(self):
        return self._rows.pop(0) if self._rows else None

    def fetchall(self):
        rows, self._rows = self._rows, []
        return rows


# Protect quoted literals/identifiers and comments while translating qmarks.
_TOKENS = re.compile(r"('(?:''|[^'])*'|\"(?:\"\"|[^\"])*\"|--[^\n]*|/\*[\s\S]*?\*/|\$([A-Za-z_][A-Za-z_0-9]*|)\$[\s\S]*?\$\2\$)")


def portable_sql(sql):
    parts = []
    pos = 0
    def translate(part):
        part = part.replace('%', '%%').replace('?', '%s')
        part = re.sub(r'\bINTEGER PRIMARY KEY AUTOINCREMENT\b', 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', part, flags=re.I)
        part = re.sub(r'\bREAL\b', 'DOUBLE PRECISION', part, flags=re.I)
        return re.sub(r'\bLIMIT\s+-1\b', 'LIMIT ALL', part, flags=re.I)
    for match in _TOKENS.finditer(sql):
        parts.extend((translate(sql[pos:match.start()]), match.group(0).replace('%', '%%')))
        pos = match.end()
    parts.append(translate(sql[pos:]))
    return ''.join(parts)


class Transaction:
    def __init__(self, store, connection):
        self.store, self.connection = store, connection

    def execute(self, sql, params=None):
        ignored = bool(re.match(r'\s*INSERT OR IGNORE\b', sql, re.I))
        if ignored:
            sql = re.sub(r'INSERT OR IGNORE', 'INSERT', sql, count=1, flags=re.I)
            sql += ' ON CONFLICT DO NOTHING'
        match = re.match(r'\s*INSERT\s+INTO\s+"?([\w]+)"?', sql, re.I)
        generated = bool(match and self.store._keys.get(match[1]) == 'id' and 'RETURNING' not in sql.upper())
        if generated:
            sql += ' RETURNING id'
        return Result(self.connection.execute(portable_sql(sql), params or []), generated)


class PostgresStore(Store):
    """Character-scoped schema with a reference-counted process-shared pool."""
    durable_indexes = True

    def __init__(self, url, *, namespace='default', pool_min_size=2, pool_max_size=20, pool_timeout=30.0):
        try:
            import psycopg
            from psycopg.rows import dict_row
            from psycopg_pool import ConnectionPool
        except ImportError:
            raise ImportError('Install charactermemory[postgres] to use PostgreSQL') from None
        if not namespace:
            raise ValueError('PostgreSQL requires a non-empty character namespace')
        self.schema = 'cm_' + hashlib.sha256(namespace.encode()).hexdigest()[:32]
        self.operational_errors = (psycopg.OperationalError, psycopg.ProgrammingError)
        self._keys = {}
        self._closed = False
        self._pool_key = (url, int(pool_min_size), int(pool_max_size), float(pool_timeout))
        with _POOL_LOCK:
            if self._pool_key not in _POOLS:
                pool = ConnectionPool(url, min_size=pool_min_size, max_size=pool_max_size,
                                      timeout=pool_timeout, kwargs={'row_factory': dict_row}, open=False)
                pool.open()
                try:
                    pool.wait(timeout=pool_timeout)
                except Exception:
                    pool.close()
                    raise ConnectionError('Could not establish PostgreSQL connection pool') from None
                _POOLS[self._pool_key] = [pool, 0]
            entry = _POOLS[self._pool_key]
            self.pool = entry[0]
            entry[1] += 1
        try:
            with self.pool.connection() as conn:
                conn.execute(f'CREATE SCHEMA IF NOT EXISTS {identifier(self.schema)}')
        except BaseException:
            self.close()
            raise

    @contextmanager
    def connection(self):
        """Native driver connection; schema selection is transaction-local."""
        if self._closed:
            raise RuntimeError('Store is closed')
        with self.pool.connection() as conn:
            conn.execute(f'SET LOCAL search_path TO {identifier(self.schema)}, public')
            yield conn

    @contextmanager
    def transaction(self, *, immediate=False):
        with self.connection() as conn:
            # These transactions protect read/modify/write world and calendar
            # operations. Scope the advisory lock to this character only.
            if immediate:
                conn.execute('SELECT pg_advisory_xact_lock(hashtextextended(%s, 0))', [self.schema])
            yield Transaction(self, conn)

    def execute(self, sql, params=None):
        with self.transaction() as tx:
            return [dict(r) for r in tx.execute(sql, params).fetchall()]

    def create_table(self, name, columns, pk='id'):
        definition = ', '.join(f'{identifier(c)} {decl}' for c, decl in columns.items())
        self.execute(f'CREATE TABLE IF NOT EXISTS {identifier(name)} ({definition})')
        self._keys[name] = next((c for c, decl in columns.items() if 'PRIMARY KEY' in decl.upper()), pk)
        for column in ('user_id', 'chat_id'):
            if column in columns and column != self._keys[name]:
                index = 'cm_lookup_' + hashlib.sha256((name + column).encode()).hexdigest()[:24]
                suffix = ', id' if 'id' in columns else ''
                self.execute(f'CREATE INDEX IF NOT EXISTS {identifier(index)} ON {identifier(name)} ({identifier(column)}{suffix})')

    def columns(self, table):
        with self.connection() as conn:
            rows = conn.execute('SELECT column_name FROM information_schema.columns WHERE table_schema=%s AND table_name=%s ORDER BY ordinal_position', [self.schema, table]).fetchall()
        return [r['column_name'] for r in rows]

    def close(self):
        with _POOL_LOCK:
            if self._closed:
                return
            self._closed = True
            entry = _POOLS[self._pool_key]
            entry[1] -= 1
            if not entry[1]:
                self.pool.close()
                del _POOLS[self._pool_key]

    def drop_namespace(self):
        """Delete this character's durable state after quiescing its users.

        Also works after close, for the server's explicit character deletion.
        This never drops the database or another character's schema.
        """
        import psycopg
        self.close()
        with psycopg.connect(self._pool_key[0], autocommit=True) as conn:
            conn.execute(f'DROP SCHEMA IF EXISTS {identifier(self.schema)} CASCADE')

    def track_table(self, table, *, key='id', collection=None):
        """Transactionally capture source writes, including raw SQL writes."""
        collection = collection or table
        with self.connection() as conn:
            conn.execute('CREATE SEQUENCE IF NOT EXISTS cm_work_revision')
            conn.execute('CREATE TABLE IF NOT EXISTS cm_index_work (collection TEXT NOT NULL, row_key TEXT NOT NULL, revision BIGINT NOT NULL, PRIMARY KEY(collection,row_key))')
            conn.execute('''CREATE OR REPLACE FUNCTION cm_queue_index() RETURNS trigger LANGUAGE plpgsql AS $$
            DECLARE item jsonb;
            BEGIN
              IF TG_OP = 'UPDATE' AND
                 (to_jsonb(OLD) - ARRAY['recall_count','last_recalled','importance','updated_at']) =
                 (to_jsonb(NEW) - ARRAY['recall_count','last_recalled','importance','updated_at']) THEN
                RETURN NULL;
              END IF;
              IF TG_OP = 'UPDATE' AND to_jsonb(OLD)->>TG_ARGV[1] IS DISTINCT FROM to_jsonb(NEW)->>TG_ARGV[1] THEN
                INSERT INTO cm_index_work(collection,row_key,revision)
                VALUES(TG_ARGV[0], to_jsonb(OLD)->>TG_ARGV[1], nextval('cm_work_revision'))
                ON CONFLICT(collection,row_key) DO UPDATE SET revision=excluded.revision;
              END IF;
              IF TG_OP = 'DELETE' THEN item := to_jsonb(OLD); ELSE item := to_jsonb(NEW); END IF;
              INSERT INTO cm_index_work(collection,row_key,revision)
              VALUES(TG_ARGV[0], item->>TG_ARGV[1], nextval('cm_work_revision'))
              ON CONFLICT(collection,row_key) DO UPDATE SET revision=excluded.revision;
              RETURN NULL;
            END $$''')
            from psycopg import sql
            conn.execute(sql.SQL('DROP TRIGGER IF EXISTS cm_queue_index ON {}').format(sql.Identifier(table)))
            conn.execute(sql.SQL('CREATE TRIGGER cm_queue_index AFTER INSERT OR UPDATE OR DELETE ON {} FOR EACH ROW EXECUTE FUNCTION cm_queue_index({}, {})').format(sql.Identifier(table), sql.Literal(collection), sql.Literal(key)))

    def pending_index(self, collection):
        return self.execute('SELECT row_key,revision FROM cm_index_work WHERE collection=?', [collection])
